#!/bin/bash

###########################
# Docker gns3             #
# version: 2.1  	  #
# Usage:	          #
# ./compileDockerGns3 tag #
###########################

#basé sur mon post: https://blog.arch-libertas.net/2020/11/test-v1-gns3-kvm-on-fedora-33/
#dans le client j'ai mis firefox pour dl les appliances
#J'ai redécouvert docker cp après, j'ai quand meme laissé firefox pour quand on clique sur download
#dans gns3 il faut dans les configs:
#Edit / Preferences / General / VNC Edit et choisir Remote Viewver
#Edit / Preferences / Qemu décocher KVM
#une fois les modifs de config effectuées, il faut redémarer le gns3serveur avec docker stop puis docker start, pas docker restart
#il faut que les 2 containers aient le repertoire en commun pour pouvoir synchroniser les fichiers de config


############
#constantes#
############

#si pas d'arguments le tag est latest
if [[ -z $2 ]] ; then
  label="latest"
else
  label=$2
fi


###########
#Fonctions#
###########

#fonction compile
# argument $1 = $1 de l'appel
#argument $2 est le nom serveur ou client
compileBase () {
    docker build -t gns3base:$1 ./gns3Base
}

compile () {
    docker build -t gns3$2:$1 ./gns3$2
}

compileAll () {
    echo "[+]Dockerisation de GNS3"
    (
	compileBase $label
	compile $label "server"
	compile $label "client"
	compile $label "toolzb0x"
    )
}

#fonction message
#affiche comment lancer les instances
message () {
echo "[-]Pour le serveur:
   docker run -d -it --net=host --privileged --volume=GNS3:/home/gns3user --name gns3server gns3server:$label"
echo "[-]Pour le client:
   docker run --net=host --privileged --env='DISPLAY' \
    --volume=GNS3:/home/gns3user \
    --volume='$HOME/.Xauthority:/root/.Xauthority:rw' \
    --name gns3client  gns3client:$label"
}

#fonction pour lancer les containers
startgns () {
    echo "[+]Demarage du serveur:"
    docker run -d -it --net=host --privileged --volume=GNS3:/home/gns3user --name gns3server gns3server:$label

    if [[ $(echo $?) -eq 0 ]]; then
	echo "[-]Serveur lancé"
    else
	echo "[!]attention, relancer le serveur manuellement, pour info voici le log"
	docker logs gns3server:$label
    fi

    echo "[+]Demarage du client"
    docker run --net=host --privileged --env="DISPLAY" --volume=GNS3:/home/gns3user --volume="$HOME/.Xauthority:/root/.Xauthority:rw" --name gns3client gns3client:$label

    if [[ $(echo $?) -eq 0 ]]; then
	echo "[-]Enjoy"
    else
	echo "[!]attention, relancer le client manuellement, pour info voici le log"
	docker logs gns3client:$label
    fi    
}


########
# Main #
########



while getopts ":bcsh" opt; do
    case ${opt} in
	b ) echo "[+] On compile et on lance"
	    compileAll
	    message
	    ;;
	s ) echo "[+] on lance les containers"
     	    startgns
	    message
	    ;;
	c ) echo "[+] on lance la compilation uniquement"
    	    compileAll
	    ;;
	h ) echo "[*] Usage: ./$0 [-c to create docker containers |-s to launch those containers| -b for both] tag"
	    ;;
    esac
done
